# .github/workflows/main.yml
name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # Action runs when a push is made to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Make sure to clone submodules (the theme)
          fetch-depth: 0    # Fetch all history for proper git operations

      # Step 2: Set up Hugo environment
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Step 3: Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # Step 4: Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: ''
